package UserDashboard;

public class Account extends javax.swing.JFrame {

    String id, name, email, status;

public Account(String uId, String uName, String uEmail, String uStatus) {
    initComponents();
    this.id = uId;
    this.name = uName;
    this.email = uEmail;
    this.status = uStatus;

    display_id.setText(id);
    display_name.setText(name);
    display_email.setText(email);
    display_status.setText(status);
}
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display_name = new javax.swing.JLabel();
        display_email = new javax.swing.JLabel();
        display_status = new javax.swing.JLabel();
        display_id = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        sales = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_nameMouseClicked(evt);
            }
        });
        jPanel1.add(display_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 70, 20));

        display_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_emailMouseClicked(evt);
            }
        });
        jPanel1.add(display_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 70, 20));

        display_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_statusMouseClicked(evt);
            }
        });
        jPanel1.add(display_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 70, 20));

        display_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_idMouseClicked(evt);
            }
        });
        jPanel1.add(display_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 70, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_50dp_18333C_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/article_50dp_18333C_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 60));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_50dp_18333C_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, 60));

        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("ACCOUNT ID:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("USERNAME:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("EMAIL:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("USER STATUS:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("ACCOUNT SETTINGS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 70, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel9.setText("jLabel8");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 70, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel10.setText("jLabel8");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 70, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel11.setText("jLabel8");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 140));

        dashboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dashboard.setForeground(new java.awt.Color(0, 153, 153));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("DASHBOARD");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, -1));

        sales.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sales.setForeground(new java.awt.Color(0, 153, 153));
        sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sales.setText("SALES");
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
        });
        jPanel1.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));

        account.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        account.setForeground(new java.awt.Color(0, 153, 153));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("ACCOUNT");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        jPanel1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, -1));

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

    new Pharmamed.Login().setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked
    
    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accountMouseClicked
    
    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
    new UserDashboard.Dashboard(id, name, email, status).setVisible(true);
    this.dispose();       // TODO add your handling code here:
    }                                    

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        new UserDashboard.Sales(id, name, email, status).setVisible(true);
        this.dispose();        // TODO add your handling code here:                                 
    }//GEN-LAST:event_dashboardMouseClicked

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
      new UserDashboard.Sales(id, name, email, status).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_salesMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

    String newName = javax.swing.JOptionPane.showInputDialog("Enter New Username:", name);
    if (newName != null && !newName.isEmpty()) {
        this.name = newName;
        jLabel13.setText(name);
    }

    String newEmail = javax.swing.JOptionPane.showInputDialog("Enter New Email:", email);
    if (newEmail != null && !newEmail.isEmpty()) {
        this.email = newEmail;
        jLabel14.setText(email);
    }

    }//GEN-LAST:event_jLabel18MouseClicked

    private void display_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_idMouseClicked

    }//GEN-LAST:event_display_idMouseClicked

    private void display_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_nameMouseClicked

    }//GEN-LAST:event_display_nameMouseClicked

    private void display_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_emailMouseClicked

    }//GEN-LAST:event_display_emailMouseClicked

    private void display_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_statusMouseClicked
 
    new UserDashboard.Account(id, name, email, status).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_display_statusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard("", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel display_email;
    private javax.swing.JLabel display_id;
    private javax.swing.JLabel display_name;
    private javax.swing.JLabel display_status;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sales;
    // End of variables declaration//GEN-END:variables
}
