/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminDashboard;

/**
 *
 * @author John Rho
 */
public class adminDashboard extends javax.swing.JFrame {
    String id, name, email, status;

    public adminDashboard(String uId, String uName, String uEmail, String uStatus) {
        initComponents();
        this.id = uId;
        this.name = uName;
        this.email = uEmail;
        this.status = uStatus;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel11.setText("jLabel8");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 260));

        AdminDashboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminDashboard.setForeground(new java.awt.Color(0, 153, 153));
        AdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboard.setText("ADMIN DASHBOARD");
        AdminDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminDashboardMouseExited(evt);
            }
        });
        jPanel1.add(AdminDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, -1));

        users.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        users.setForeground(new java.awt.Color(0, 153, 153));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setText("USERS");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));

        account.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        account.setForeground(new java.awt.Color(0, 153, 153));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("ACCOUNT");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        jPanel1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, -1));

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardMouseClicked
   new AdminDashboard.adminDashboard(id, name, email, status).setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDashboardMouseClicked

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        new AdminDashboard.Users(id, name, email, status).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked

        new AdminDashboard.Account(id, name, email, status).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_accountMouseClicked

    private void AdminDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardMouseExited

    }//GEN-LAST:event_AdminDashboardMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard("", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel account;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
