package AdminDashboard;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;
import config.config;

import javax.swing.JOptionPane;
import config.Session;
import Pharmamed.Login;

public class Users extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String id, name, email, status;

    public Users(String uId, String uName, String uEmail, String uStatus) {
    if (Session.getInstance().getUid() == null) {
        JOptionPane.showMessageDialog(null, "Login first!");
        new Login().setVisible(true);
        this.dispose();
    } else {
        initComponents();
        config conf = new config();
        conn = conf.connectDB();
        this.id = uId;
        this.name = uName;
        this.email = uEmail;
        this.status = uStatus;
        updateTable();
        
        
        
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchbar = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        add = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        AdminDashboard = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 230, 200));

        searchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchbarKeyReleased(evt);
            }
        });
        jPanel1.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 190, 30));

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 60, 30));

        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 60, 30));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 50, 30));

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, 30));

        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (1).png"))); // NOI18N
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 40, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skyblueverylight.png"))); // NOI18N
        jLabel11.setText("jLabel8");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 260));

        AdminDashboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminDashboard.setForeground(new java.awt.Color(0, 153, 153));
        AdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminDashboard.setText("ADMIN DASHBOARD");
        AdminDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDashboardMouseClicked(evt);
            }
        });
        jPanel1.add(AdminDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, -1));

        users.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        users.setForeground(new java.awt.Color(0, 153, 153));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setText("USERS");
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, -1));

        account.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        account.setForeground(new java.awt.Color(0, 153, 153));
        account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        account.setText("ACCOUNT");
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        jPanel1.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, -1));

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/49579.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 270, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  public void updateTable() {
    try {
        String sql = "SELECT a_id, name, email, type, status FROM tbl_accounts";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    
    private void manageUser(String action, String u_id) {
    javax.swing.JTextField nameF = new javax.swing.JTextField();
    javax.swing.JTextField emailF = new javax.swing.JTextField();
    javax.swing.JComboBox<String> statusF = new javax.swing.JComboBox<>(new String[]{"Active", "Pending"});

    if (action.equals("Edit")) {
        int row = jTable1.getSelectedRow();
        nameF.setText(jTable1.getValueAt(row, 1).toString());
        emailF.setText(jTable1.getValueAt(row, 2).toString());
        statusF.setSelectedItem(jTable1.getValueAt(row, 3).toString());
    }

    Object[] inputFields = { "Name:", nameF, "Email:", emailF, "Status:", statusF };

    int result = javax.swing.JOptionPane.showConfirmDialog(null, inputFields, action + " User", javax.swing.JOptionPane.OK_CANCEL_OPTION);
    
    if (result == javax.swing.JOptionPane.OK_OPTION) {
        try {
            String sql = action.equals("Add") 
                ? "INSERT INTO tbl_accounts (name, email, status) VALUES (?, ?, ?)"
                : "UPDATE tbl_accounts SET name=?, email=?, status=? WHERE a_id=?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, nameF.getText());
            pst.setString(2, emailF.getText());
            pst.setString(3, statusF.getSelectedItem().toString());
            if (action.equals("Edit")) pst.setString(4, u_id);

            pst.executeUpdate();
            updateTable();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, e);
        }
    }
}
    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        new AdminDashboard.Users(id, name, email, status).setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_usersMouseClicked

    private void AdminDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDashboardMouseClicked
        new AdminDashboard.adminDashboard(id, name, email, status).setVisible(true);
        this.dispose();        // TODO add your                                                                                                            
    }//GEN-LAST:event_AdminDashboardMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
        new AdminDashboard.Account(id, name, email, status).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        manageUser("Add", null);
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int row = jTable1.getSelectedRow();
    if (row != -1) {
        manageUser("Edit", jTable1.getValueAt(row, 0).toString());
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Select a user first");
    }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

    int row = jTable1.getSelectedRow();
    if (row != -1) {
        int confirm = javax.swing.JOptionPane.showConfirmDialog(null, "Delete this record?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                pst = conn.prepareStatement("DELETE FROM tbl_accounts WHERE a_id = ?");
                pst.setString(1, jTable1.getValueAt(row, 0).toString());
                pst.executeUpdate();
                updateTable();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed

    searchbar.setText("");
    updateTable();
    }//GEN-LAST:event_refreshActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void searchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbarKeyReleased
                                    
    try {
        String query = searchbar.getText();
        String sql = "SELECT a_id, name, email, status FROM tbl_accounts WHERE name LIKE ? OR email LIKE ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, "%" + query + "%");
        pst.setString(2, "%" + query + "%");
        rs = pst.executeQuery();
        jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs)); 
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_searchbarKeyReleased
    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Users("", "", "", "").setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashboard;
    private javax.swing.JLabel account;
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField searchbar;
    private javax.swing.JButton searchbutton;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
